import json
from pathlib import Path

from services.converter.app.models.document_package import DocumentAsset
from services.converter.app.models.document_package import DocumentPackage


def write_document_package(package: DocumentPackage, output_dir: Path) -> None:
    # Python offsets count code points; Flutter String indexes UTF-16 code units.
    if (package.sourceInfo or {}).get("offsetEncoding") != "utf-16":
        for block in package.blocks:
            text = block.text or ""
            offsets = [0]
            for char in text:
                offsets.append(offsets[-1] + len(char.encode("utf-16-le")) // 2)
            for span in [*block.textSpans, *block.referenceSpans]:
                if not 0 <= span.start <= span.end <= len(text):
                    raise ValueError(f"Invalid text span in {block.id}")
                span.start, span.end = offsets[span.start], offsets[span.end]
        package.sourceInfo = {**(package.sourceInfo or {}), "offsetEncoding": "utf-16", "textNormalized": True}
    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / "assets").mkdir(exist_ok=True)

    _write_asset_files(package.assets, output_dir)

    (output_dir / "package.json").write_text(
        package.model_dump_json(indent=2),
        encoding="utf-8",
    )
    source_map = {
        "documentId": package.documentId,
        "blocks": [
            {"blockId": block.id, "anchor": block.anchor.model_dump() if block.anchor else None}
            for block in package.blocks
        ],
    }
    (output_dir / "source-map.json").write_text(
        json.dumps(source_map, indent=2),
        encoding="utf-8",
    )


def _write_asset_files(assets: list[DocumentAsset], output_dir: Path) -> None:
    package_root = output_dir.resolve()
    for asset in assets:
        relative_path = Path(asset.relativePath)
        if relative_path.is_absolute():
            raise ValueError(f"Asset path must be relative: {asset.relativePath}")

        asset_path = (output_dir / relative_path).resolve()
        if not asset_path.is_relative_to(package_root):
            raise ValueError(f"Asset path escapes package directory: {asset.relativePath}")

        asset_path.parent.mkdir(parents=True, exist_ok=True)
        if asset_path.exists():
            continue

        asset_path.write_text(_placeholder_asset_text(asset), encoding="utf-8")


def _placeholder_asset_text(asset: DocumentAsset) -> str:
    lines = [
        f"Label: {asset.label}",
        f"Kind: {asset.kind}",
    ]
    if asset.caption:
        lines.append(f"Caption: {asset.caption}")
    lines.append("Source: Placeholder generated by the MVP PDF converter; original visual extraction is not yet available.")
    return "\n".join(lines) + "\n"
